# Generated by Django 2.1.1 on 2018-09-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccuser',
            name='friends',
            field=models.ManyToManyField(related_name='_ccuser_friends_+', to='api.CCUser'),
        ),
    ]
