# Generated by Django 2.1.1 on 2018-09-19 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ccuser_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ccuser',
            name='cc_username',
        ),
    ]
